### ISSUE TITLE
Trends in Cumulate Organic Matter Render Concern

### ISSUE THREAD

**Issue by NodakJ** [ncss-tech/ISSR-800#15]
Calculations and Review of Soil Organic Matter does not seem to be conveying the correct information.  Compared my own calculations and valu1 cumulative profile SOC soc0_999 (x1.72 to render OM v OC) and results were inconsistent with regional trends in known area ND & N. MN.
![som_ssurgo](https://user-images.githubusercontent.com/25324934/35058594-5b742fac-fbb0-11e7-8dcc-54fcbd0c001f.jpg)
![spropsee](https://user-images.githubusercontent.com/25324934/35058882-32c7a600-fbb1-11e7-9ae4-586475adf1aa.JPG)

**Comment by NodakJ** [comment]
Thanks for reviewing comments.  From the description, I do believe the CaCO3 matter is addressed.  However, I am less confident the matter of SOM in Northern Forests of MN & WI is resolved through NULLs.  The trends of concern above are rendering from SSURGO where NULLs in OM% are rare.  The concerning trends also play out in soils of similar depth.  I estimate the trends displayed in SOM to be more indicative of relative trends in the upper layer vs the profile as a whole, as described in the documentation.  In the upper horizon in northern forests you may find inconsistency in populating an O in one area vs. an A in an adjacent (see major discrepancies in North Central Wisconsin, to illustrate a relative inconsistent OM population at the surface).  However, that inconsistency is commonly muted in a whole profile weighting, as a thin O & thick E vs a thick A and thinner E balance out with total OM.  A quick comparison of results of ISSR800 SOM vs gSSURGO valu1 soc0_999 seems to illustrate the discrepancy well.  Another example to view, there is more total OM in tallgrass prairie benchmark landscapes (Clarion-Nicollet) of South Central MN, vs a similar concept in a mixed northern forest soil (Warba-Stuntz), but it is showing opposite trends in ISSR800.

**Comment by dylanbeaudette** [comment]
Thanks for the update. Map unit keys, or other examples will help me track down the inconsistencies. Contact me at work and I can send you the new stack of grids: the soil-properties application has not been updated.

Making gridded maps of soil properties is a compromise between smoothing over the data issues that can be addressed vs. trying to do the work of 10+ yrs of update mapping. I typically error on the side of displaying the data as they are, after accounting for NULL vs. 0 and so on.

**Comment by dylanbeaudette** [comment]
An update from Joe:


```
-90.1616, 45.81381 – this 800m cell is completely contained by a single SSURGO polygon
ISSR800 om_kg_sq_m - 1.771088

Gridded SSURGO Valu1 Table Soil Organic Carbon (g/sq m) – 132157
Converted from SOC to SOM 132157*1.72 = 227310
Unit Conversion to KG – 227.31

SSURGO Map Unit Key – 421089
[hzthk_r] * [om_r] * ([sieveno10_r] /100)* [dbthirdbar_r]
```

cokey | # Hz | Profile OM | Component % | compname | mukey | Weighted OM |  
-- | -- | -- | -- | -- | -- | -- | --
15311988 | 2 | 2,032.55 | 35 | Greenwood | 421089 | 711.39 |  
15311989 | 2 | 2,892.80 | 35 | Loxley | 421089 | 1,012.48 |  
15311990 | 3 | 1,853.59 | 30 | Dawson | 421089 | 556.08 |  
  |   |   |   |   | Total | 2,279.95 | g/cm2
  |   |   |   |   |   | 227.99 | kg/m2

So, anyway I was able to replicate the gSSURGO valu1 logic here (with some error probably related to the variations of OC/OM conversions) in contrast to the results in ISSR800.  You mentioned a matter of Oven Dry vs. 1/3 bar dB, perhaps this is the key.  Oven Dry is not a required data field for Organic Horizons, and is often omitted.  So in this example, it seems the ISSR is reporting the total carbon from the one horizon of the one mineral floored component.

**Comment by dylanbeaudette** [comment]
And, good [reminder to review these notes on the topic](https://ncss-tech.github.io/sda-lib/chapters/Soil%20Organic%20Carbon%20Stocks.html) via Skye and Jason.

Related to 1/3bar Db in #19

**Comment by dylanbeaudette** [comment]
Replacing 

```SQL
SELECT cokey, round(comppct_r, 2) as comppct, caco3_kg_sq_m, om_kg_sq_m, ph_025, max_om, sar, ec, ec_025 
FROM ssurgo_component_data 
WHERE mukey = '1395735' 
order by comppct_r DESC;
```


Using `dbovendry_r` which is missing for many (most) O horizons:
```
  cokey   | comppct | caco3_kg_sq_m | om_kg_sq_m | ph_025 | max_om | sar | ec | ec_025
----------+---------+---------------+------------+--------+--------+-----+----+--------
 16476021 |    0.25 |             0 |   2.457665 |        |    0.7 |   0 |  0 |      0
 16476024 |    0.25 |               |            |        |    0.8 |   0 |  0 |      0
 16476020 |    0.20 |               |            |        |   0.62 |   0 |  0 |      0
 16476025 |    0.15 |             0 |     6.2403 |        |    0.5 |   0 |  0 |      0
```

Using `dbthirdbar_r` which seems to be safer and likely more "realistic":
```
  cokey   | comppct | caco3_kg_sq_m | om_kg_sq_m | ph_025 | max_om | sar | ec | ec_025
----------+---------+---------------+------------+--------+--------+-----+----+--------
 16476021 |    0.25 |             0 | 172.435545 |        |    0.7 |   0 |  0 |      0
 16476024 |    0.25 |             0 |     311.36 |        |    0.8 |   0 |  0 |      0
 16476020 |    0.20 |             0 |    226.548 |        |   0.62 |   0 |  0 |      0
 16476025 |    0.15 |             0 |   87.85848 |        |    0.5 |   0 |  0 |      0
```

**Comment by dylanbeaudette** [comment]
Grids re-made, results below:

```
SELECT * FROM ssurgo_grid_mapunit WHERE mukey = '1395735' 
ORDER BY area_wt DESC;

grid_gid |  mu_gid  |  mukey  |        area_wt         |   gid
----------+----------+---------+------------------------+----------
 13328681 | 35293598 | 1395735 |                 640000 |  2447287
 13324955 | 35293598 | 1395735 |                 640000 |  2440458
 13328680 | 35293598 | 1395735 |       634190.469204243 |  2447285
 13328675 | 35293598 | 1395735 |       611687.203836441 | 80893112
 13332409 | 35293598 | 1395735 |       604645.613428593 |  2455073
 13328676 | 35293598 | 1395735 |       603957.781061649 |  2447262
 

SELECT * FROM ssurgo_grid_mapunit WHERE grid_gid = 13328681;

 grid_gid |  mu_gid  |  mukey  | area_wt |   gid
----------+----------+---------+---------+---------
 13328681 | 35293598 | 1395735 |  640000 | 2447287
 

SELECT gid, cokey, om_kg_sq_m_wt, caco3_kg_sq_m_wt 
FROM ssurgo_component_weights where gid = 2447287;

   gid   |  cokey   |        om_kg_sq_m_wt        |      caco3_kg_sq_m_wt
---------+----------+-----------------------------+-----------------------------
 2447287 | 16476025 |  96000.00000000000000000000 |  96000.00000000000000000000
 2447287 | 16476024 | 160000.00000000000000000000 | 160000.00000000000000000000
 2447287 | 16476021 | 160000.00000000000000000000 | 160000.00000000000000000000
 2447287 | 16476020 | 128000.00000000000000000000 | 128000.00000000000000000000

SELECT grid_gid, number_components, caco3_kg_sq_m, om_kg_sq_m 
FROM ssurgo_gridded_properties where grid_gid = 13328681;

 grid_gid | number_components | caco3_kg_sq_m |    om_kg_sq_m
----------+-------------------+---------------+------------------
 13328681 |                 4 |             0 | 211.102656764706


SELECT 
sum(caco3_kg_sq_m * caco3_kg_sq_m_wt) / NULLIF(sum(caco3_kg_sq_m_wt), 0) as caco3_kg_sq_m,
sum(om_kg_sq_m * om_kg_sq_m_wt) / NULLIF(sum(om_kg_sq_m_wt), 0) as om_kg_sq_m
FROM
(
SELECT cokey, round(comppct_r, 2) AS comppct, caco3_kg_sq_m, om_kg_sq_m from ssurgo_component_data where mukey = '1395735'
) AS a
JOIN 
(
SELECT gid, cokey, om_kg_sq_m_wt, caco3_kg_sq_m_wt from ssurgo_component_weights where gid = 2447287
) AS b USING (cokey)
GROUP BY gid
;

 caco3_kg_sq_m |    om_kg_sq_m
---------------+------------------
             0 | 211.102656764706

```

**Comment by NodakJ** [comment]
Issue appears resolved in updated om_kg_sq_m ISSR800 soil grid.

**Comment by dylanbeaudette** [comment]
Thanks for checking. This was one of the last major problems.
